### ISSUE TITLE
Yum Application

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/yum#87]
Here is the application for YUM with mongoose and express:
https://github.com/chris-A-phillips/yum-express

There are no views rendered everything is served as json in this package. 

I'm currently learning how to put Angular on top of the mean stack. I don't know why I get so stuck on convention but I've watched countless youtube videos and tutorials these past 3 days. read tons of style guides, and only now feel like I'm getting a handle on how this should all look and work. 

Thanks for...........

Anyway, I really don't like that the crud for my /resturants takes up almost 90 lines. I feel like that's a lot considering I only included minor error handling and status mutations.

What are validations?

Where do they go? 

Should they be a promise in our restful functions?

You can use postmaster like I did to verify all the routes work and that they perform crud on the restaurant model of the database.

**Comment by nayana487** [comment]
👍
